### ISSUE TITLE
warp get: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by irq0** [minio/warp#268]
Running a get benchmark in 0.7.1 segfaults:

```
[2023-06-13T08:12:07Z] podman run --network=host minio/warp:v0.7.1 get --host=localhost:7480 --access-key=test --secret-key=test

warp: Preparing server.
Uploading 2500 objectspanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f5832]

goroutine 1 [running]:
github.com/minio/warp/pkg/bench.(*Get).Prepare(0xc0000f5340, {0xd63a30?, 0xc000038070})
        github.com/minio/warp/pkg/bench/get.go:149 +0x632
github.com/minio/warp/cli.runBench(0xc00027e340, {0xd63d40, 0xc0000f5340})
        github.com/minio/warp/cli/benchmark.go:165 +0x502
github.com/minio/warp/cli.mainGet(0xc00027e340)
        github.com/minio/warp/cli/get.go:89 +0x316
github.com/minio/cli.HandleAction({0xb38c80?, 0xc908a0?}, 0x3?)
        github.com/minio/cli@v1.24.2/app.go:490 +0x5a
github.com/minio/cli.Command.Run({{0xc32f96, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc3de19, 0x15}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:242 +0x9b7
github.com/minio/cli.(*App).Run(0xc0002401c0, {0xc000034140, 0x5, 0x5})
        github.com/minio/cli@v1.24.2/app.go:260 +0x827
github.com/minio/warp/cli.Main({0xc000034140?, 0x5, 0x5})
        github.com/minio/warp/cli/cli.go:81 +0x239
main.main()
        github.com/minio/warp/main.go:27 +0x2e
```

On 0.7.0 warp get runs fine:
```
[2023-06-13T08:16:48Z] podman run --network=host minio/warp:v0.7.0 get --host=localhost:7480 --access-key=test --secret-key=test --objects=10

warp: Preparing server.
Uploading 10 objectswarp: Starting benchmark in 3s...
warp: Benchmark starting...
...
```

**Comment by klauspost** [comment]
Reproduced.

**Comment by akshay8043** [comment]
Thanks, I am also facing the same issue.
